---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: alibabacloud-eip-operator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: alibabacloud-eip-operator-webhook-service
      namespace: alibabacloud-eip-operator-system
      path: /validate-eip-alibabacloud-com-v1alpha1-eip
  failurePolicy: Fail
  name: veip.kb.io
  rules:
  - apiGroups:
    - eip.alibabacloud.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - eips
  sideEffects: None
